# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kidneyapplication

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kidneyapplication.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a97d465c13e2488f818db7904120a128 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ef6840ad13c54f0585ff7f3e3718b5dd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kidneyapplication.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a97d465c13e2488f818db7904120a128 }}/kidneyapplication:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kidneyapplication'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_85688d70c2174397a93cca9c00c0c108 }}
        images: 'kidneyapplication.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a97d465c13e2488f818db7904120a128 }}/kidneyapplication:${{ github.sha }}'